### ISSUE TITLE
Duplicate ingressAddresses in Listener status when using NodePort ListenerClass

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/listener-operator#229]
### Affected Stackable version

0.0.0-dev

### Current and expected behavior

Raised in https://github.com/stackabletech/kafka-operator/pull/443#issuecomment-2388310867

This is a Kafka bootstrap listener for 3 brokers. As we have 3 Pods it looks like the same entry is added three time in `status.ingressAddresses`. We probably want to de-duplicate entries in that list.

```yaml
apiVersion: listeners.stackable.tech/v1alpha1
kind: Listener
metadata:
  name: simple-kafka-broker-default-bootstrap
  namespace: default
# ...
spec:
  className: external-stable
  extraPodSelectorLabels: {}
  ports:
  - name: metrics
    port: 9606
    protocol: TCP
  - name: kafka
    port: 9092
    protocol: TCP
  publishNotReadyAddresses: null
status:
  ingressAddresses:
  - address: 172.18.0.2
    addressType: IP
    ports:
      kafka: 32639
      metrics: 30178
  - address: 172.18.0.2
    addressType: IP
    ports:
      kafka: 32639
      metrics: 30178
  - address: 172.18.0.2
    addressType: IP
    ports:
      kafka: 32639
      metrics: 30178
  nodePorts:
    kafka: 32639
    metrics: 30178
  serviceName: simple-kafka-broker-default-bootstrap
```

### Would you like to work on fixing this bug?

None
